TP3-LUNACLARASO/TP3-LUNACLARASO/Controllers/CadeteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TP3_LunaClaraso.Models;

namespace TP3_LunaClaraso.Controllers
{
    public class CadeteController : Controller
    {
        static int id = 0;
        private readonly ILogger<CadeteController> _logger;
        private readonly BDTemporal _BD;
        private readonly RepositorioCadete _cd;

        public CadeteController(ILogger<CadeteController> logger, RepositorioCadete cd)
        {
            _logger = logger;
            _cd = cd;

        }

        // GET: CadeteController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult AltaCadete()
        {
            return View();
        }
        public IActionResult VerCadetes()
        {
            return View(_cd.MostrarCadetes());
        }
        
        public IActionResult DarAlta(string nombre, string direccion, string telefono)
        {
            Cadete nuevoCadete = new (++id, nombre, direccion, telefono);
            //_BD.Cadeteria.Cadetes.Add(nuevoCadete);
            _cd.guardarCadete(nuevoCadete);
            return View("Index", _cd.MostrarCadetes());
        }/*
        public IActionResult BorrarCadete(int id)
        {
            int i = 0;
            foreach (var item in _BD.Cadeteria.Cadetes)
            {
                if (item.Id == id)
                {
                    _BD.EliminarCadete();
                    break;
                }
                i++;
            }
            return View("Index", _BD.Cadeteria.Cadetes);
        }
        */
        public IActionResult ModificarCadete(int id)
        {
            Cadete cadete =_cd.MostrarCadeteID(id);
            return View(cadete);
        }
        
        public IActionResult Modify(Cadete cd)
        {
            _cd.ModificarCadete(cd);

            return View("Index", _cd.MostrarCadetes());

        }
    }
}

TP3-LUNACLARASO/TP3-LUNACLARASO/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using TP3_LunaClaraso.Models;

namespace TP3_LunaClaraso.Controllers
{
    public class PedidoController : Controller
    {
        static int id = 0;
        private readonly ILogger<PedidoController> _logger;
        private readonly BDTemporal _BD;

        public PedidoController(ILogger<PedidoController> logger, BDTemporal BD)
        {
            _logger = logger;
            _BD = BD;
        }

        // GET: PedidoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PedidoController/Details/5
        public ActionResult AltaPedido()
        {
            return View(_BD.Cadeteria.Cadetes);
        }

        // GET: PedidoController/Create
        public ActionResult VerClientes()
        {
            return View(_BD.Cadeteria.Clientes);
        }

        public IActionResult VerPedidos()
        {
            
            return View(_BD.Cadeteria);
        }
        public IActionResult DarAlta(int nro, string observacion, int idCliente, string nombre, string direccion, long telefono)
        {/*
            Pedidos nuevoPedido = new(++nro,observacion, idCliente, nombre,direccion,telefono);
            _BD.Cadeteria.Pedidos.Add(nuevoPedido);
            Cliente nuevoCliente = new(++nro, nombre,  direccion,  telefono);
            _BD.Cadeteria.Clientes.Add(nuevoCliente);
            
            return View("VerPedidos", _BD.Cadeteria);
            */
            int ultimoNum = 100;
            if (_BD.Cadeteria.Pedidos.Count() > 0)
            {
                ultimoNum = _BD.Cadeteria.Pedidos.Max(x => x.Nro);
            }
            ultimoNum++;
            Pedidos nuevoPedido = new Pedidos(ultimoNum, observacion, idCliente, nombre, direccion, telefono);
            _BD.Cadeteria.Pedidos.Add(nuevoPedido);
            _BD.GuardarPedido(_BD.Cadeteria.Pedidos);
            return View("VerPedidos", _BD.Cadeteria);
        }
        public IActionResult BorrarCadete(int idpedido)
        {
            _BD.Cadeteria.Pedidos.RemoveAll(pedido => pedido.Nro == idpedido);

            _BD.EliminarCadete();

            return View("Index", _BD.Cadeteria.Pedidos);
        }
        public IActionResult AsignarCadete(int idPedido, int idCadete)
        {
            //QuitarPedidoDeCadete(idPedido);

            if (idCadete != 0)
            {
                Cadete cadete = _BD.Cadeteria.Cadetes.Where(a => a.Id == idCadete).First();
                Pedidos pedido = _BD.Cadeteria.Pedidos.Where(b => b.Nro == idPedido).First();
                cadete.ListadoDePedidos1.Add(pedido);
            }

            return View("VerPedidos", _BD.Cadeteria);
        }

        public IActionResult EliminarPedido(int idPedido)
        {
            eliminarUnPedido(idPedido);
            
            return View("VerPedidos", _BD.Cadeteria);
        }

        public void eliminarUnPedido(int id)
        {
            Pedidos pedido = _BD.Cadeteria.Pedidos.Where(a => a.Nro == id).First();
            _BD.Cadeteria.Pedidos.Remove(pedido);

            quitarPedidoCadete(pedido);
        }

        public void quitarPedidoCadete(Pedidos pedido)
        {
            _BD.Cadeteria.Cadetes.ForEach(cad => cad.ListadoDePedidos1.Remove(pedido));
        }

        // POST: PedidoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PedidoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PedidoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PedidoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PedidoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TP3-LUNACLARASO/TP3-LUNACLARASO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TP3_LunaClaraso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Servicio de Cadeteria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Cadete" asp-action="AltaCadete">Agregar Cadete</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Pedido" asp-action="AltaPedido">Agregar Pedido</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Cadete" asp-action="VerCadetes">Ver Cadetes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Pedido" asp-action="VerClientes">Ver Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Pedido" asp-action="VerPedidos">Ver Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Luna Clarasó - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>